### PR TITLE
eu-cetral-1 region + proper encoding

### PR DESCRIPTION
**Pull request by gusto2**
Added eu-central-1 region and proper signature request encoding

### CODE REVIEW

**Comment by pcorliss** [comment]
This looks good, I'll take a look tonight, fix some formatting issues and add back in some of the deleted lines.

What was the signature encoding issue? Occasional special chars causing URL breakage?

**Comment by gusto2** [comment]
Hi,
btw nice page.. 
updates - 
1. the region was hardcoded for the canonical string, needs to be parametrized
2.eu-central-1 region added, maybe we should add all supported AWS regions :) 
3. the parameters should be url encoded. Maybe the signature hex string doesn't need to, however I consider it as good practice (the signature was base64 encoded for v2 AWS signed requests so I encode anything generated)

indeed - I've deleted the GA snippet, you're welcome to put it back..

g.

**Comment by pcorliss** [comment]
Sorry for dropping this. I ended up adding all the updated regions as well as fixing the region selection issue. I don't believe the encoding is necessary, but if you have a test case I'll be happy to take another look.

**Comment by pcorliss** [comment]
CDN URL Fix for crypto: 0734cbc29eb1baaa79c002810a2088357fd8669e
Region selection fix: 9433880bd9511f284ce53998840f6fae806aa540

**Pull request closed without merging**
